url: "https://lightweightlsat.com" 
baseurl: "" # the subpath of your site, e.g. /blog
title: "Lightweight LSAT"


exclude: [".gitignore", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt", ".htaccess"]

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "default"