site_name: the lightweight LSAT
site_url: https://lightweightlsat.com
repo_url: https://github.com/gpdowney/lightweightLSAT
repo_name: lightweightLSAT
edit_uri: edit/mkdocs/docs/

theme:
  name: material
  custom_dir: overrides
  font: 
    text: 'B612'
  icon:
    logo: material/hiking
    repo: fontawesome/brands/git-alt
  palette:
      scheme: default
      primary: white
      accent: teal
  features:
    - toc.follow
    - navigation.top
    - navigation.indexes
    - navigation.tabs
    - navigation.footer
    - navigation.expand
    - content.action.view
    - content.action.edit

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: false
      enabled: false
  - search
  - literate-nav:
      nav_file: navigation.md

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: '#'
      permalink_title: Link to this section
      title: on this page
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols:
      trademark: true
      copyright: false
      registered: true
      care_of: true
      plusminus: true
      arrows: true
      notequal: true
      fractions: true
      ordinal_numbers: true
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: >
  All original material licensed <a href="https://creativecommons.org/licenses/by-sa/4.0/" rel="license">CC BY-SA 4.0.</a><br>
  The LSAC does not approve of this website. And I do not approve of the LSAC.

site_description: A minimalist guide to the LSAT.